### ISSUE TITLE
License issue

### ISSUE THREAD

**Issue by PeterDaveHello** [christian-fei/Timeline.css#9]
Hi @christian-fei, I saw that the readme said this project is under MIT license(https://github.com/christian-fei/Timeline.css#mit-licensed), but in the commit to add package.json(https://github.com/christian-fei/Timeline.css/commit/ec62643ee809f6b7a750d6dc277564ddacc1ed02#diff-b9cfc7f2cdf78a7f4b91a753d10865a2R14), it's ISC
```diff
+{
+  "name": "timeline.css",
+  "version": "1.0.0",
+  "description": "Timeline The best way to create your own Timeline, with just CSS! Share life and work events with Timeline.css! Sass and SCSS port too!",
+  "main": "index.js",
+  "scripts": {
+    "test": "echo \"Error: no test specified\" && exit 1"
+  },
+  "repository": {
+    "type": "git",
+    "url": "git+https://github.com/christian-fei/Timeline.css.git"
+  },
+  "author": "Christian Fei",
+  "license": "ISC",
+  "bugs": {
+    "url": "https://github.com/christian-fei/Timeline.css/issues"
+  },
+  "homepage": "https://github.com/christian-fei/Timeline.css#readme"
+}
```

So is this project under multiple licenses or this is a mistake? Thanks!

**Comment by christian-fei** [comment]
Hello,
thanks, this was a mistake

**Comment by PeterDaveHello** [comment]
https://github.com/christian-fei/Timeline.css/commit/0266e3d32c30a71b032dc93099799b64608e96f5#diff-b9cfc7f2cdf78a7f4b91a753d10865a2
